### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by janhohenheim** [vleue/bevy_pathmesh#10]
Seeing as, in my opinion, the project is quite usable as-is, what do you think about releasing it? :)

**Comment by mockersf** [comment]
I was waiting for a few more features that I wanted to do, mostly https://github.com/vleue/polyanya/issues/22, https://github.com/vleue/polyanya/issues/23 and https://github.com/vleue/polyanya/issues/24, but they can come later.

I'm adding documentation and doing some cleanups in #11 to prepare a release 👍

**Comment by mockersf** [comment]
done! https://crates.io/crates/bevy_pathmesh
