### ISSUE TITLE
docs.rs link is broken

### ISSUE THREAD

**Issue by janhohenheim** [vleue/bevy_pathmesh#13]
https://docs.rs/bevy_pathmesh says "The requested crate does not exist"

**Comment by mockersf** [comment]
It's in the build queue: https://docs.rs/releases/queue

**Comment by janhohenheim** [comment]
Ah, TIL! I'm curious, how do you deprioritize a crate?

**Comment by mockersf** [comment]
the crates.io has a rule for some of the big crate releaser (more than 30 crates released at the same type) that works with a prefix on the crate name I think. You can see them in the queue as (priority: -1). The goal is that big project releases don't block individual crates from big documented
