### ISSUE TITLE
Bake pathmeshes

### ISSUE THREAD

**Issue by janhohenheim** [vleue/bevy_pathmesh#9]
Since they can no longer be modified after the `PathMesh` creation anyways, might as well bake them on creation.

**Comment by mockersf** [comment]
for the moment, mesh baking (or not) is controlled by a feature on polynya: https://github.com/vleue/polyanya/blob/main/src/lib.rs#L209

I would prefer to keep a way to not bake a mesh if wanted

**Comment by janhohenheim** [comment]
Ah, I didn't catch the default baking in polyanya, makes sense!
